Repository voila-dashboards/voila, pull requests merged in 2021-10, with the labels that each got.

#983 Fix `post` function in log template
  share/jupyter/voila/templates/base/log.macro.html.j2
Labels: bug

#987 Pin openssl to v1.1.1l
  .github/workflows/main.yml
Labels: maintenance

#988 Automated Changelog Entry for 0.2.16 on main
  CHANGELOG.md
Labels: documentation

#990 Automated Changelog Entry for 0.3.0a0 on main
  CHANGELOG.md
Labels: documentation

#993 Fix wrong base_url
  voila/notebook_renderer.py
Labels: bug

#995 Bot skips Binder badge comment
  .github/workflows/benchmark-report.yml
Labels: maintenance

#999 Add support for query variables in preheat kernel mode
  docs/source/customize.rst
  setup.cfg
  tests/app/preheat_activation_test.py
  tests/notebooks/preheat/pre_heat.ipynb
  voila/app.py
  voila/handler.py
  voila/notebook_renderer.py
  voila/query_parameters_handler.py
  voila/utils.py
  voila/voila_kernel_manager.py
Labels: enhancement

#1007 Pass version spec as a GitHub Actions input
  .github/workflows/check-release.yml
Labels: maintenance
