Repository voila-dashboards/voila, pull requests merged in 2021-01, with the labels that each got.

#789 Test on Python 3.9
  .github/workflows/main.yml
Labels: CI

#797 Describe cell execution timeout in docs
  docs/source/customize.rst
Labels: Documentation

#798 Add CI workflow for packaging
  .github/workflows/packaging.yml
Labels: CI

#802 Update to JupyterLab 3.0 final
  .github/workflows/build.yml
  packages/jupyterlab-preview/package.json
  packages/jupyterlab-preview/yarn.lock
  pyproject.toml
Labels: jupyterlab-preview
