Repository voila-dashboards/voila, pull requests merged in 2021-12, with the labels that each got.

#1038 Enforce labels on PRs
  .github/workflows/enforce-labels.yml
Labels: maintenance

#1039 Backport PR #1037 on branch main (Updating Heroku deploy instructions)
  docs/source/deploy.rst
Labels: documentation

#1040 Update tests on Windows
  .github/workflows/main.yml
  tests/app/preheat_activation_test.py
  tests/conftest.py
Labels: testing, maintenance

#1042 Automated Changelog Entry for 0.3.0 on main
  CHANGELOG.md
Labels: documentation

#1043 Use `maintainer-tools` base setup action, update Python versions on CI
  .github/workflows/binder-on-pr.yml
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .github/workflows/main.yml
  .github/workflows/packaging.yml
  .github/workflows/ui-tests.yml
Labels: maintenance

#1045 Turn off debug mode and remove warnings for `many_iopub_messages_test.py`
  .github/workflows/main.yml
  tests/app/cgi-test.py
  tests/app/cwd_subdir_test.py
  tests/app/many_iopub_messages_test.py
  tests/app/notebooks_test.py
  tests/app/serve_directory_test.py
  tests/app/tree_test.py
  tests/server/cwd_subdir_test.py
  tests/server/tree_test.py
Labels: testing, maintenance

#1048 UI-tests: Update ipympl screenshots
  .github/workflows/ui-tests.yml
  ui-tests/tests/voila.test.ts
  ui-tests/tests/voila.test.ts-snapshots/ipympl-linux.png
Labels: testing, maintenance

#766 Feature: fetch all widgets in one single comm message using the control channel
  packages/voila/src/manager.ts
Labels: enhancement

#1025 Implement async generator based Voila get handler
  voila/handler.py
  voila/notebook_renderer.py
Labels: enhancement
