Repository voila-dashboards/voila, pull requests merged in 2021-09, with the labels that each got.

#934 Improve Galata tests, update the reference screenshot
  ui-tests/package.json
  ui-tests/reference-output/screenshots/voila_basics.png
  ui-tests/tests/voila.test.ts
  ui-tests/yarn.lock
Labels: testing, maintenance

#935 Handle the case when one widget model fails to be created
  packages/voila/src/manager.ts
Labels: bug

#933 Update @jupyterlab/services dependency to version 6.1.8
  packages/voila/package.json
  yarn.lock
Labels: enhancement

#931 Render Javascript output
  packages/voila/package.json
  packages/voila/src/index.ts
  packages/voila/src/manager.ts
  packages/voila/src/rendermime.ts
  share/jupyter/voila/templates/base/static/main.js
  yarn.lock
Labels: enhancement

#922 http_header_envs option to include http headers as an env var (following CGI standards)
  voila/configuration.py
  voila/handler.py
Labels: enhancement

#944 add JupyterLab trove classifiers
  setup.py
Labels: maintenance

#943 Update to Jupyter Packaging 0.10
  .github/workflows/build.yml
  .github/workflows/packaging.yml
  MANIFEST.in
  RELEASE.md
  pyproject.toml
  setup.cfg
  setup.py
Labels: maintenance

#913 Add check-release step on CI
  .github/workflows/check-release.yml
  CONTRIBUTING.md
  RELEASE.md
  docs/source/contribute.rst
  docs/source/deploy.rst
  package.json
  pyproject.toml
  voila/_version.py
Labels: maintenance

#946 Update the UI Tests setup
  .eslintignore
  .eslintrc.js
  .github/workflows/ui-tests.yml
  .gitignore
  .prettierignore
  ui-tests/galata-config.json
  ui-tests/jupyter_server_config.py
  ui-tests/package.json
  ui-tests/playwright.config.js
  ui-tests/reference-output/screenshots/voila_basics.png
  ui-tests/tests/voila.test.ts
  ui-tests/tests/voila.test.ts-snapshots/basics-linux.png
  ui-tests/yarn.lock
Labels: testing, maintenance

#951 Add `allow-popups` and `allow-modals` to the preview sandbox
  packages/jupyterlab-preview/src/preview.tsx
Labels: enhancement, jupyterlab-preview

#952 Update to lerna 4
  package.json
  yarn.lock
Labels: maintenance

#954 Add a script to bump the version
  .bumpversion.cfg
  .github/workflows/check-release.yml
  RELEASE.md
  packages/voila/package.json
  pyproject.toml
  scripts/bump-version.py
  setup.cfg
  voila/_version.py
Labels: maintenance

#957 Minor release fixes
  RELEASE.md
  scripts/bump-version.py
Labels: documentation, maintenance

#959 Default to clean all for the preview extension
  packages/jupyterlab-preview/package.json
  pyproject.toml
Labels: maintenance

#960 Clean up bump version script
  .github/workflows/check-release.yml
  RELEASE.md
  scripts/bump-version.py
Labels: maintenance

#963 Make `INotebookTracker` optional
  packages/jupyterlab-preview/src/index.ts
Labels: enhancement

#962 Add UI test and benchmark report
  .github/workflows/benchmark-report.yml
  .github/workflows/ui-tests.yml
  .gitignore
  notebooks/multiple_widgets.ipynb
  ui-tests/package.json
  ui-tests/playwright.config.js
  ui-tests/tests/notebooks/basics.ipynb
  ui-tests/tests/utils.ts
  ui-tests/tests/voila.test.ts
  ui-tests/tests/voila.test.ts-snapshots/basics-linux.png
  ui-tests/tests/voila.test.ts-snapshots/bqplot-linux.png
  ui-tests/tests/voila.test.ts-snapshots/gridspecLayout-linux.png
  ui-tests/tests/voila.test.ts-snapshots/interactive-linux.png
  ui-tests/tests/voila.test.ts-snapshots/ipympl-linux.png
  ui-tests/tests/voila.test.ts-snapshots/ipyvolume-linux.png
  ui-tests/tests/voila.test.ts-snapshots/multiple-widgets-linux.png
  ui-tests/tests/voila.test.ts-snapshots/query-strings-linux.png
  ui-tests/voila-benchmark-expected.json
  ui-tests/yarn.lock
Labels: testing, maintenance

#964 Upload the distributions built by the releaser
  .github/workflows/check-release.yml
Labels: testing, maintenance

#965 Automated Changelog Entry for 0.2.13 on master
  CHANGELOG.md
Labels: documentation

#966 Update release instructions to recommend using the releaser
  RELEASE.md
Labels: documentation

#968 Rename to `main`
  .github/pull_request_template.md
  .github/workflows/check-release.yml
  RELEASE.md
  docs/source/using.rst
Labels: maintenance

#612 Send kernel shutdown request manually on beforeunload
  share/jupyter/voila/templates/base/static/main.js
Labels: bug

#969 Cleanup executor resources after execution
  voila/handler.py
Labels: bug

#970 Automated Changelog Entry for 0.2.14 on main
  CHANGELOG.md
Labels: documentation

#972 Use `sendBeacon` to send kernel shutdown request.
  share/jupyter/voila/templates/base/static/main.js
  tests/app/shutdown_kernel_test.py
  voila/app.py
  voila/server_extension.py
  voila/shutdown_kernel_handler.py
Labels: bug

#981 0.2.15 Release fixes
  CHANGELOG.md
  packages/voila/package.json
Labels: maintenance

#978 Update reference screenshot for ipympl notebook
  ui-tests/tests/voila.test.ts-snapshots/ipympl-linux.png
Labels: maintenance

#982 Fix example code in `basics.ipynb`
  notebooks/basics.ipynb
Labels: documentation
