Repository voila-dashboards/voila, pull requests merged in 2022-02, with the labels that each got.

#1085 Add script to automatically reset the `stable` branch on release
  pyproject.toml
  scripts/reset-stable.sh
Labels: maintenance

#1083 Add bot for updating Galata references
  .github/pull_request_template.md
  .github/workflows/ui-tests.yml
  .github/workflows/update_galata_references.yaml
  setup.cfg
  ui-tests/tests/voila.test.ts-snapshots/basics-linux.png
  ui-tests/tests/voila.test.ts-snapshots/bqplot-linux.png
  ui-tests/tests/voila.test.ts-snapshots/gridspecLayout-linux.png
  ui-tests/tests/voila.test.ts-snapshots/interactive-linux.png
  ui-tests/tests/voila.test.ts-snapshots/ipympl-linux.png
  ui-tests/tests/voila.test.ts-snapshots/ipyvolume-linux.png
  ui-tests/tests/voila.test.ts-snapshots/multiple-widgets-linux.png
  ui-tests/tests/voila.test.ts-snapshots/query-strings-linux.png
  ui-tests/tests/voila.test.ts-snapshots/reveal-linux.png
Labels: maintenance

#1089 Lab theme handling
  docs/source/customize.rst
  setup.cfg
  share/jupyter/voila/templates/base/tree.html
  share/jupyter/voila/templates/lab/page.html
  share/jupyter/voila/templates/lab/tree.html
  ui-tests/playwright.config.js
  ui-tests/tests/voila.test.ts
  ui-tests/tests/voila.test.ts-snapshots/basics-classic-linux.png
  ui-tests/tests/voila.test.ts-snapshots/basics-dark-linux.png
  ui-tests/tests/voila.test.ts-snapshots/basics-miami-linux.png
  ui-tests/tests/voila.test.ts-snapshots/voila-tree-classic-linux.png
  ui-tests/tests/voila.test.ts-snapshots/voila-tree-dark-linux.png
  ui-tests/tests/voila.test.ts-snapshots/voila-tree-light-linux.png
  ui-tests/tests/voila.test.ts-snapshots/voila-tree-miami-linux.png
  voila/app.py
  voila/server_extension.py
  voila/treehandler.py
  voila/utils.py
Labels: enhancement

#1092 Update JupyterLab extension logo
  packages/jupyterlab-preview/style/voila.svg
Labels: enhancement

#1096 Bump `css-loader` and `style-loader``
  packages/jupyterlab-preview/style/index.css
  packages/voila/package.json
  yarn.lock
Labels: bug

#1094 small fixes to jupyterlab voila extension
  packages/jupyterlab-preview/src/preview.tsx
  packages/jupyterlab-preview/style/base.css
Labels: enhancement, jupyterlab-preview

#1098 Automated Changelog Entry for 0.3.2 on main
  CHANGELOG.md
Labels: documentation

#1099 Remove extra tick from the Changelog
  CHANGELOG.md
Labels: documentation
