Repository voila-dashboards/voila, pull requests merged in 2022-10, with the labels that each got.

#1224 Update nbclient pinning
  pyproject.toml
Labels: dependencies, maintenance

#1161 Update nbconvert pinning
  pyproject.toml
  tests/notebooks/print_parameterized.ipynb
  ui-tests/tests/voila.test.ts-snapshots/interactive-linux.png
  ui-tests/tests/voila.test.ts-snapshots/query-strings-linux.png
  voila/exporter.py
Labels: enhancement, dependencies, maintenance

#1226 Automated Changelog Entry for 0.4.0b0 on main
  CHANGELOG.md
Labels: documentation

#1231 Automated Changelog Entry for 0.4.0rc0 on main
  CHANGELOG.md
Labels: documentation

#1232 Remove pin on `jupyter_releaser`
  pyproject.toml
Labels: maintenance

#1233 Revert "Automated Changelog Entry for 0.4.0rc0 on main"
  CHANGELOG.md
Labels: documentation

#1239 Add upper bound on jupyter_client dependency
  pyproject.toml
Labels: bug

#1234 Update nbclient
  pyproject.toml
Labels: dependencies, maintenance

#1242 Automated Changelog Entry for 0.4.0 on main
  CHANGELOG.md
Labels: documentation

#846 Switch to a lab-based app for the Voila frontend
  .binder/environment.yml
  .eslintignore
  .gitignore
  .prettierignore
  docs/source/contribute.rst
  docs/source/using.rst
  notebooks/mimerenderers.ipynb
  packages/jupyterlab-preview/src/preview.tsx
  packages/voila/package.json
  packages/voila/publicpath.js
  packages/voila/src/app.ts
  packages/voila/src/bootstrap.ts
  packages/voila/src/global.d.ts
  packages/voila/src/index.ts
  packages/voila/src/kernel.ts
  packages/voila/src/loader.ts
  packages/voila/src/main.ts
  packages/voila/src/manager.ts
  packages/voila/src/mathjax.ts
  packages/voila/src/output.ts
  packages/voila/src/plugins.ts
  packages/voila/src/rendermime.ts
  packages/voila/src/shell.ts
  packages/voila/src/typings.d.ts
  packages/voila/style.css
  packages/voila/style/index.css
  packages/voila/tsconfig.json
  packages/voila/webpack.config.js
  pyproject.toml
  requirements-visual-test.txt
  share/jupyter/voila/templates/base/static/main.js
  share/jupyter/voila/templates/base/voila_setup.macro.html.j2
  share/jupyter/voila/templates/classic/index.html.j2
  share/jupyter/voila/templates/lab/index.html.j2
  share/jupyter/voila/templates/reveal/index.html.j2
  tests/app/config_paths_test.py
  tests/app/nbextensions_test.py
  tests/app/template_sanity_test.py
  tests/configs/general/voila.json
  tests/execute_output_test.py
  tests/notebooks/output.ipynb
  tests/test_template/share/jupyter/voila/templates/test_template/index.html.j2
  tests/test_template/share/jupyter/voila/templates/test_template/voila.tpl
  ui-tests/tests/voila.test.ts
  ui-tests/tests/voila.test.ts-snapshots/ipyvolume-linux.png
  ui-tests/tests/voila.test.ts-snapshots/voila-tree-classic-linux.png
  ui-tests/tests/voila.test.ts-snapshots/voila-tree-dark-linux.png
  ui-tests/tests/voila.test.ts-snapshots/voila-tree-light-linux.png
  ui-tests/tests/voila.test.ts-snapshots/voila-tree-miami-linux.png
  voila/app.py
  voila/configuration.py
  voila/exporter.py
  voila/handler.py
  voila/notebook_renderer.py
  voila/server_extension.py
  voila/utils.py
  voila/voila_kernel_manager.py
  yarn.lock
Labels: enhancement, new, api-change

#1247 Automated Changelog Entry for 0.5.0a0 on main
  CHANGELOG.md
Labels: documentation
