Repository voila-dashboards/voila, pull requests merged in 2022-01, with the labels that each got.

#1052 Fix environment.yml file location in the README
  README.md
  RELEASE.md
Labels: documentation

#1053 Lab template: fix body tag
  share/jupyter/voila/templates/lab/index.html.j2
  share/jupyter/voila/templates/reveal/index.html.j2
Labels: bug, enhancement

#1054 Try fixing UI tests
  ui-tests/tests/voila.test.ts-snapshots/basics-linux.png
  ui-tests/tests/voila.test.ts-snapshots/bqplot-linux.png
  ui-tests/tests/voila.test.ts-snapshots/gridspecLayout-linux.png
  ui-tests/tests/voila.test.ts-snapshots/interactive-linux.png
  ui-tests/tests/voila.test.ts-snapshots/ipympl-linux.png
  ui-tests/tests/voila.test.ts-snapshots/ipyvolume-linux.png
  ui-tests/tests/voila.test.ts-snapshots/multiple-widgets-linux.png
  ui-tests/tests/voila.test.ts-snapshots/query-strings-linux.png
  ui-tests/tests/voila.test.ts-snapshots/reveal-linux.png
Labels: maintenance

#1060 Remove traitlets 4 test, add missing traitlets dependency and drop Python 3.6 support
  .github/workflows/main.yml
  setup.cfg
Labels: maintenance

#1057 Add more Jinja macros
  share/jupyter/voila/templates/base/voila_setup.macro.html.j2
  share/jupyter/voila/templates/lab/index.html.j2
Labels: enhancement

#1058 Fix element style display
  share/jupyter/voila/templates/lab/index.html.j2
Labels: enhancement

#1062 Automatically download labvariables CSS instead of shipping them
  .gitignore
  pyproject.toml
  setup.py
  share/jupyter/voila/templates/classic/static/labvariables.css
  share/jupyter/voila/templates/classic/static/materialcolors.css
  share/jupyter/voila/templates/reveal/static/labvariables.css
  share/jupyter/voila/templates/reveal/static/materialcolors.css
  ui-tests/tests/voila.test.ts-snapshots/reveal-linux.png
Labels: maintenance

#1068 Pin `ipympl` to `0.8.7`
  .github/workflows/ui-tests.yml
  ui-tests/tests/voila.test.ts-snapshots/ipympl-linux.png
Labels: testing

#1064 Allow all lab templates to use the lab theme
  share/jupyter/voila/templates/lab/browser-open.html
  share/jupyter/voila/templates/lab/page.html
  share/jupyter/voila/templates/lab/tree.html
  voila/app.py
  voila/exporter.py
  voila/treehandler.py
  voila/utils.py
Labels: enhancement

#1073 Fix file redirect error
  ui-tests/tests/voila.test.ts-snapshots/basics-linux.png
  ui-tests/tests/voila.test.ts-snapshots/bqplot-linux.png
  ui-tests/tests/voila.test.ts-snapshots/gridspecLayout-linux.png
  ui-tests/tests/voila.test.ts-snapshots/interactive-linux.png
  ui-tests/tests/voila.test.ts-snapshots/ipympl-linux.png
  ui-tests/tests/voila.test.ts-snapshots/ipyvolume-linux.png
  voila/handler.py
  voila/notebook_renderer.py
Labels: bug
