Repository voila-dashboards/voila, pull requests merged in 2022-08, with the labels that each got.

#1180 Update Google App Engine deploy docs
  docs/source/deploy.rst
Labels: documentation

#1185 Fix inifinite loop in property access
  voila/exporter.py
Labels: bug

#1191 Troubleshoot failing `macos` check on CI
  .github/workflows/main.yml
  .github/workflows/packaging.yml
Labels: maintenance

#1193 Fix CI
  tests/app/preheat_multiple_notebooks_test.py
  tests/execute_output_test.py
  tests/notebooks/output.ipynb
Labels: maintenance

#1181 Render read-only notebook
  packages/jupyterlab-preview/src/index.ts
  packages/jupyterlab-preview/src/preview.tsx
Labels: enhancement
