Repository voila-dashboards/voila, pull requests merged in 2022-03, with the labels that each got.

#1108 Add theme handling to error pages
  share/jupyter/voila/templates/base/error.html
  share/jupyter/voila/templates/lab/error.html
  share/jupyter/voila/templates/lab/page.html
  ui-tests/tests/voila.test.ts
  ui-tests/tests/voila.test.ts-snapshots/404-classic-linux.png
  ui-tests/tests/voila.test.ts-snapshots/404-dark-linux.png
  ui-tests/tests/voila.test.ts-snapshots/404-linux.png
  voila/handler.py
  voila/treehandler.py
Labels: enhancement

#1111 Automated Changelog Entry for 0.3.3 on main
  CHANGELOG.md
Labels: documentation

#1109 feat: make request info available in env for preheated kernels
  docs/source/customize.rst
  voila/app.py
  voila/handler.py
  voila/request_info_handler.py
  voila/utils.py
Labels: enhancement

#1118 Fix CI
  voila/app.py
  voila/utils.py
Labels: maintenance

#1121 Fix ipywidgets 7.7 incompatibility issue
  packages/voila/package.json
  packages/voila/src/manager.ts
  packages/voila/src/utils.ts
  ui-tests/tests/voila.test.ts-snapshots/basics-dark-linux.png
  ui-tests/tests/voila.test.ts-snapshots/basics-linux.png
  ui-tests/tests/voila.test.ts-snapshots/basics-miami-linux.png
  ui-tests/tests/voila.test.ts-snapshots/gridspecLayout-linux.png
  yarn.lock
Labels: maintenance

#1127 Fix `jinja2 3.1.0` compatibility issue
  setup.cfg
  ui-tests/tests/voila.test.ts-snapshots/reveal-linux.png
  voila/exporter.py
  voila/utils.py
Labels: maintenance

#1125 Fix wait_for_request
  docs/source/customize.rst
  voila/utils.py
  voila/voila_kernel_manager.py
Labels: maintenance

#1129 feat: support all kernel ServerConnection options
  packages/voila/src/kernel.ts
Labels: enhancement

#1134 Automated Changelog Entry for 0.3.5 on main
  CHANGELOG.md
Labels: documentation
