Repository voila-dashboards/voila, pull requests merged in 2022-07, with the labels that each got.

#1150 [tests] rerun failed tests 2 times in CI
  .github/workflows/main.yml
  setup.cfg
Labels: testing, maintenance

#1167 adding nbextension path to voila config object
  voila/app.py
  voila/configuration.py
  voila/server_extension.py
Labels: enhancement

#1163 Update jupyter_server
  setup.cfg
  tests/notebooks/many_iopub_messages.ipynb
Labels: maintenance

#1171 The cling tests appear to hang on OSX
  .github/workflows/main.yml
Labels: bug

#1173 Automated Changelog Entry for 0.3.6 on main
  CHANGELOG.md
Labels: documentation

#724 reenable prelaunch-hook
  docs/source/customize.rst
  setup.cfg
  tests/app/prelaunch_hook_papermill_test.py
  tests/app/prelaunch_hook_test.py
  tests/notebooks/print_parameterized.ipynb
  voila/app.py
  voila/handler.py
  voila/notebook_renderer.py
Labels: enhancement

#1176 Add Voila app port to kernel env
  tests/app/preheat_with_query_string_test.py
  voila/voila_kernel_manager.py
Labels: enhancement

#1175 Add Voila configuration option for default kernel environmental variables
  docs/source/customize.rst
  tests/app/preheat_default_kernel_env_test.py
  tests/notebooks/preheat/default_env_variables.ipynb
  voila/app.py
  voila/voila_kernel_manager.py
Labels: enhancement
