Repository voila-dashboards/voila, pull requests merged in 2023-02, with the labels that each got.

#1281 Fix existing CI
  .github/workflows/main.yml
  .github/workflows/ui-tests.yml
Labels: maintenance

#1282 Fix broken test by rolling back file
  tests/execute_output_test.py
  tests/notebooks/output.ipynb
Labels: maintenance

#1187 Voilite POC
  .binder/postBuild
  .gitignore
  packages/voila/src/index.ts
  packages/voila/src/main.ts
  packages/voila/src/plugins.ts
  packages/voilite/package.json
  packages/voilite/publicpath.js
  packages/voilite/src/app.ts
  packages/voilite/src/bootstrap.ts
  packages/voilite/src/global.d.ts
  packages/voilite/src/index.ts
  packages/voilite/src/manager.ts
  packages/voilite/src/plugins.ts
  packages/voilite/src/tree.ts
  packages/voilite/src/treebootstrap.ts
  packages/voilite/src/utils.ts
  packages/voilite/style.css
  packages/voilite/style/index.css
  packages/voilite/tsconfig.json
  packages/voilite/webpack.config.js
  pyproject.toml
  share/jupyter/voila/templates/base/spinner.macro.html.j2
  share/jupyter/voila/templates/base/voila_setup.macro.html.j2
  share/jupyter/voila/templates/classic/index.html.j2
  share/jupyter/voila/templates/lab/index.html.j2
  share/jupyter/voila/templates/lab/tree.html
  share/jupyter/voila/templates/reveal/index.html.j2
  voila/handler.py
  voila/notebook_renderer.py
  voila/treehandler.py
  voila/utils.py
  voila/voilite/__init__.py
  voila/voilite/app.py
  voila/voilite/exporter.py
  voila/voilite/static/services.js
  voila/voilite/voilite_tree_exporter.py
  yarn.lock
Labels: enhancement, new

#1289 Revert "Voilite POC"
  .binder/postBuild
  .gitignore
  packages/voila/src/index.ts
  packages/voila/src/main.ts
  packages/voila/src/plugins.ts
  packages/voilite/package.json
  packages/voilite/publicpath.js
  packages/voilite/src/app.ts
  packages/voilite/src/bootstrap.ts
  packages/voilite/src/global.d.ts
  packages/voilite/src/index.ts
  packages/voilite/src/manager.ts
  packages/voilite/src/plugins.ts
  packages/voilite/src/tree.ts
  packages/voilite/src/treebootstrap.ts
  packages/voilite/src/utils.ts
  packages/voilite/style.css
  packages/voilite/style/index.css
  packages/voilite/tsconfig.json
  packages/voilite/webpack.config.js
  pyproject.toml
  share/jupyter/voila/templates/base/spinner.macro.html.j2
  share/jupyter/voila/templates/base/voila_setup.macro.html.j2
  share/jupyter/voila/templates/classic/index.html.j2
  share/jupyter/voila/templates/lab/index.html.j2
  share/jupyter/voila/templates/lab/tree.html
  share/jupyter/voila/templates/reveal/index.html.j2
  voila/handler.py
  voila/notebook_renderer.py
  voila/treehandler.py
  voila/utils.py
  voila/voilite/__init__.py
  voila/voilite/app.py
  voila/voilite/exporter.py
  voila/voilite/static/services.js
  voila/voilite/voilite_tree_exporter.py
  yarn.lock
Labels: maintenance

#1290 Extendable voila
  packages/voila/src/index.ts
  packages/voila/src/main.ts
  packages/voila/src/plugins.ts
  share/jupyter/voila/templates/base/spinner.macro.html.j2
  share/jupyter/voila/templates/base/voila_setup.macro.html.j2
  share/jupyter/voila/templates/classic/index.html.j2
  share/jupyter/voila/templates/lab/index.html.j2
  share/jupyter/voila/templates/lab/tree.html
  share/jupyter/voila/templates/reveal/index.html.j2
  voila/handler.py
  voila/notebook_renderer.py
  voila/treehandler.py
  yarn.lock
Labels: enhancement

#1292 Update check-release workflow
  .github/workflows/check-release.yml
  pyproject.toml
  scripts/bump-version.py
Labels: maintenance
