Repository voila-dashboards/voila, pull requests merged in 2023-06, with the labels that each got.

#1328 Install yarn<3 in dev env
  docs/source/contribute.rst
Labels: maintenance

#1336 Backport PR #1334 on branch 0.3.x (Do not clean up resources after execution)
  .github/workflows/build.yml
  .github/workflows/main.yml
  voila/notebook_renderer.py
Labels: bug

#1337 0.3.x: Fix OpenSSL issue
  .github/workflows/build.yml
  .github/workflows/main.yml
  .github/workflows/ui-tests.yml
  packages/jupyterlab-preview/package.json
  packages/jupyterlab-preview/webpack.lab.config.js
  packages/voila/webpack.config.js
Labels: bug

#1333 Add nbconvert version check
  .github/workflows/main.yml
  ui-tests/playwright.config.js
  ui-tests/tests/voila.test.ts
  voila/exporter.py
Labels: bug

#1330 Separate Tornado handlers into their own class
  voila/app.py
  voila/handler.py
  voila/server_extension.py
  voila/tornado/handler.py
  voila/tornado/treehandler.py
  voila/treehandler.py
Labels: enhancement

#1339 Backport PR #1281 on branch 0.4.x (Fix existing CI)
  .github/workflows/main.yml
  .github/workflows/ui-tests.yml
Labels: maintenance

#1340 Backport PR #1300 on branch 0.4.x (Pin yarn to fix tests)
  .github/workflows/main.yml
Labels: maintenance

#1335 Backport PR #1334 on branch 0.4.x (Do not clean up resources after execution)
  .github/workflows/main.yml
  packages/jupyterlab-preview/package.json
  packages/jupyterlab-preview/webpack.lab.config.js
  packages/voila/package.json
  packages/voila/webpack.config.js
  voila/notebook_renderer.py
Labels: bug

#1334 Do not clean up kernel resources after execution
  voila/notebook_renderer.py
Labels: bug
