Repository voila-dashboards/voila, pull requests merged in 2023-08, with the labels that each got.

#1364 Fix linting
  docs/source/_static/main_stylesheet.css
  docs/source/deploy.rst
  yarn.lock
Labels: maintenance

#1362 Update mathjax setting
  packages/voila/package.json
  packages/voila/src/main.ts
  voila/app.py
  voila/handler.py
  voila/notebook_renderer.py
  voila/utils.py
  voila/voila_kernel_manager.py
  yarn.lock
Labels: bug, enhancement

#1367 Update `blacklist` and `whitelist` keywords
  docs/source/customize.rst
  tests/app/preheat_multiple_notebooks_test.py
  tests/configs/preheat/voila.json
  tests/notebooks/preheat/denylisted.ipynb
  voila/__init__.py
  voila/app.py
  voila/configuration.py
  voila/handler.py
  voila/server_extension.py
  voila/static_file_handler.py
  voila/tornado/treehandler.py
  voila/utils.py
  voila/voila_kernel_manager.py
Labels: maintenance

#1240 Add tests for Python 3.11
  .github/workflows/main.yml
  pyproject.toml
  voila/utils.py
  voila/voila_kernel_manager.py
Labels: maintenance

#1370 Do not load disabled extension.
  voila/utils.py
Labels: bug

#1371 Mention Voici in documentation
  docs/source/index.rst
Labels: documentation

#1381 Update documentation
  docs/Makefile
  docs/changelog.md
  docs/conf.py
  docs/contribute.md
  docs/customize.md
  docs/deploy.md
  docs/doc-requirements.txt
  docs/environment.yml
  docs/index.md
  docs/install.md
  docs/make.bat
  docs/metadata-template-classic.png
  docs/metadata-theme-classic.png
  docs/source/_static/main_stylesheet.css
  docs/source/contribute.rst
  docs/source/customize.rst
  docs/source/deploy.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/using.rst
  docs/using.md
  docs/voila-logo.svg
  pyproject.toml
  readthedocs.yml
Labels: documentation

#1382 Add highlights section to changelog
  CHANGELOG.md
Labels: documentation

#1383 Add link to use the railway template
  docs/deploy.md
Labels: documentation

#1385 Add voila style to tree page
  share/jupyter/voila/templates/lab/index.html.j2
  share/jupyter/voila/templates/lab/tree.html
  share/jupyter/voila/templates/reveal/index.html.j2
  voila/tornado/treehandler.py
Labels: bug
