Repository voila-dashboards/voila, pull requests merged in 2023-03, with the labels that each got.

#1296 refactor: typo + rst styling
  docs/source/customize.rst
Labels: documentation

#1298 Add releaser workflows to the repo
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  RELEASE.md
Labels: maintenance

#1300 Pin yarn to fix tests
  .github/workflows/main.yml
Labels: maintenance

#1299 Update the tree view so that URLs are correct for Voici
  share/jupyter/voila/templates/base/tree.html
  share/jupyter/voila/templates/lab/tree.html
Labels: enhancement

#1301 Reveal template: Use proper routine for including JS asset
  share/jupyter/voila/templates/reveal/index.html.j2
Labels: bug

#1268 Refactor styling
  .eslintignore
  .gitignore
  hatch_build.py
  packages/voila/package.json
  packages/voila/src/main.ts
  packages/voila/style.css
  packages/voila/style/index.css
  packages/voila/style/index.js
  packages/voila/webpack.config.js
  pyproject.toml
  share/jupyter/voila/templates/base/tree.html
  share/jupyter/voila/templates/classic/index.html.j2
  share/jupyter/voila/templates/lab/index.html.j2
  share/jupyter/voila/templates/reveal/index.html.j2
  ui-tests/tests/voila.test.ts-snapshots/reveal-linux.png
  yarn.lock
Labels: maintenance

#1249 Make use of JupyterLab mimetype renderers
  notebooks/bokeh.ipynb
  notebooks/mimerenderers.ipynb
  packages/voila/package.json
  packages/voila/src/app.ts
  packages/voila/src/index.ts
  packages/voila/src/main.ts
  packages/voila/src/manager.ts
  packages/voila/src/output.ts
  packages/voila/src/plugins.ts
  pyproject.toml
  requirements-visual-test.txt
  share/jupyter/voila/templates/classic/index.html.j2
  share/jupyter/voila/templates/lab/index.html.j2
  share/jupyter/voila/templates/reveal/index.html.j2
  ui-tests/tests/voila.test.ts
  ui-tests/tests/voila.test.ts-snapshots/basics-classic-linux.png
  ui-tests/tests/voila.test.ts-snapshots/bokeh-linux.png
  ui-tests/tests/voila.test.ts-snapshots/mimerenderers-linux.png
  ui-tests/tests/voila.test.ts-snapshots/reveal-linux.png
  ui-tests/tests/voila.test.ts-snapshots/voila-tree-classic-linux.png
  ui-tests/tests/voila.test.ts-snapshots/voila-tree-dark-linux.png
  ui-tests/tests/voila.test.ts-snapshots/voila-tree-light-linux.png
  ui-tests/tests/voila.test.ts-snapshots/voila-tree-miami-linux.png
  voila/exporter.py
  voila/handler.py
  voila/utils.py
  voila/voila_kernel_manager.py
  yarn.lock
Labels: enhancement

#1310 Clean up the check release workflow
  .github/workflows/check-release.yml
Labels: maintenance
