Repository voila-dashboards/voila, pull requests merged in 2024-04, with the labels that each got.

#1456 Update CHANGELOG
  CHANGELOG.md
Labels: documentation

#1457 Disambiguate voilà frontend via html data attributes
  share/jupyter/voila/templates/base/page.html
  share/jupyter/voila/templates/classic/index.html.j2
  share/jupyter/voila/templates/lab/index.html.j2
  share/jupyter/voila/templates/reveal/index.html.j2
Labels: enhancement

#1462 allow nbclient 0.10
  pyproject.toml
Labels: maintenance
