Repository voila-dashboards/voila, pull requests merged in 2024-10, with the labels that each got.

#1497 Update and improve CI
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .github/workflows/main.yml
  .github/workflows/packaging.yml
  .github/workflows/ui-tests.yml
Labels: maintenance

#1498 Bring back support for jupyter-server 1
  .github/workflows/ui-tests.yml
  pyproject.toml
  requirements-visual-test.txt
  voila/app.py
Labels: maintenance

#1496 Fix mathjax default url and bump ipywidgets packages
  packages/voila/package.json
  packages/voila/src/tools.ts
  ui-tests/package.json
  ui-tests/tests/voila.test.ts
  voila/utils.py
  yarn.lock
Labels: bug

#1491 0.4.x: Fix markdown rendering logic
  .gitignore
  package.json
  packages/voila/package.json
  packages/voila/src/index.ts
  packages/voila/src/manager.ts
  packages/voila/src/mathjax.ts
  share/jupyter/voila/templates/base/static/main.js
  share/jupyter/voila/templates/classic/index.html.j2
  share/jupyter/voila/templates/lab/index.html.j2
  share/jupyter/voila/templates/reveal/index.html.j2
  ui-tests/tests/voila.test.ts
  yarn.lock
Labels: bug

#1489 Support progressive rendering
  .github/workflows/check-release.yml
  .github/workflows/main.yml
  .github/workflows/packaging.yml
  .github/workflows/ui-tests.yml
  .github/workflows/update_galata_references.yaml
  docs/customize.md
  packages/voila/src/app.ts
  packages/voila/src/plugins/widget/index.ts
  packages/voila/src/plugins/widget/manager.ts
  packages/voila/src/plugins/widget/plugins.ts
  packages/voila/src/plugins/widget/tools.ts
  packages/voila/src/voilaplugins.ts
  share/jupyter/voila/templates/base/spinner.macro.html.j2
  share/jupyter/voila/templates/base/voila_setup.macro.html.j2
  tests/app/conftest.py
  tests/app/progressive_rendering_activation_test.py
  tests/app/progressive_rendering_test.py
  ui-tests/package.json
  ui-tests/playwright.config.js
  ui-tests/tests/voila.test.ts
  ui-tests/tests/voila.test.ts-snapshots/404-dark-linux.png
  ui-tests/tests/voila.test.ts-snapshots/404-linux.png
  ui-tests/tests/voila.test.ts-snapshots/bokeh-linux.png
  ui-tests/tests/voila.test.ts-snapshots/gridspecLayout-linux.png
  ui-tests/tests/voila.test.ts-snapshots/ipympl-linux.png
  ui-tests/tests/voila.test.ts-snapshots/voila-tree-classic-linux.png
  ui-tests/tests/voila.test.ts-snapshots/voila-tree-dark-linux.png
  ui-tests/tests/voila.test.ts-snapshots/voila-tree-light-linux.png
  ui-tests/yarn.lock
  voila/app.py
  voila/configuration.py
  voila/handler.py
  voila/notebook_renderer.py
  voila/request_info_handler.py
  voila/server_extension.py
  voila/tornado/execution_request_handler.py
  voila/tornado/kernel_websocket_handler.py
  voila/utils.py
Labels: enhancement

#1495 Custom page config hook
  docs/customize.md
  tests/app/page_config_hook_test.py
  voila/app.py
  voila/configuration.py
  voila/handler.py
  voila/notebook_renderer.py
  voila/tornado/treehandler.py
  voila/utils.py
  voila/voila_kernel_manager.py
Labels: enhancement

#1502 Remove `any` type
  packages/voila/src/plugins/outputs/tools.ts
Labels: maintenance

#1504 Update widgets 7 packages
  package.json
  packages/widgets_manager7/package.json
  yarn.lock
Labels: maintenance
